### ISSUE TITLE
Use constant environment variables

### ISSUE THREAD

**Issue by webnickell** [purplenoodlesoop/purple-starter#101] opened 2022-08-27 19:20 UTC
I discover this project and find interesting idea, but I suppose we can do it little be better.
```dart
abstract class IEnvironmentStorage {
  Environment get environment;
  String get sentryDsn;
}

class EnvironmentStorage implements IEnvironmentStorage {
  const EnvironmentStorage();

  @override
  Environment get environment => Environment.values.byName(
        const String.fromEnvironment('ENVIRONMENT'),
      );

  @override
  String get sentryDsn => const String.fromEnvironment('SENTRY_DSN');
}
```
Firstly, property environment, would be compute every time when we access to it, because `byName` is not constant expression.
I propose use another variant.
```
class Environment {
  const Environment._();
  static const _flavor = String.fromEnvironment(
    'flavor',
    defaultValue: 'dev',
  );
  static const isDevMode = _flavor == 'dev';
  static const isProdMode = _flavor == 'prod';
  static const isDemoMode = _flavor == 'demo';
  static const flavor = isDevMode
      ? Flavor.dev
      : isProdMode
          ? Flavor.prod
          : Flavor.demo;
}
```
Yes, here we use static fields. I understand that in this case we can't create different implementations, but I think we don't need it here. We don't need abstractions for abstractions. But we achieve compile time optimizations,
```
class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Environment.isAndroid ? const AndroidStyledWidgets() : const IosStyledWidgets();
  }
}
```
In this example, we cut of all IosStyled widgets from app, when we provide variable platform=android. But with current approach in this project this feature is unused.

**Comment by purplenoodlesoop** [comment] 2022-08-27 19:50
Duplicate of #71

**Closed by purplenoodlesoop** 2022-08-27 19:50 UTC
Labels: question
